from enum import auto, Enum


class BaseValue(Enum):
    BARRIER_DURATION        = auto()
    BARRIER_SHIELDING       = auto()
    LIFT_DURATION           = auto()
    SINGULARITY_DURATION    = auto()
    STASIS_DURATION         = auto()
    THROW_FORCE             = auto()
    WARP_DURATION           = auto()


class Modifier(Enum):
    ACCURACY_REGEN          = auto()
    ALL_DAMAGE              = auto()
    ALL_DURATION            = auto()
    ASSAULT_RIFLE_ACCURACY  = auto()
    ASSAULT_RIFLE_DAMAGE    = auto()
    BARRIER_DURATION        = auto()
    BARRIER_HASTE           = auto()
    BARRIER_REGEN           = auto()
    BARRIER_SHIELDING       = auto()
    BIOTIC_PROTECTION       = auto()
    DAMAGE_PROTECTION       = auto()
    FIRST_AID_HASTE         = auto()
    FIRST_AID_HEALING       = auto()
    HEALTH                  = auto()
    HEALTH_REGEN            = auto()
    HEAVY_ARMOR_DR          = auto()
    HEAVY_ARMOR_HARDENING   = auto()
    HULL_REPAIR             = auto()
    LIFT_DURATION           = auto()
    LIFT_HASTE              = auto()
    LIGHT_ARMOR_DR          = auto()
    LIGHT_ARMOR_HARDENING   = auto()
    MAX_ACCURACY            = auto()
    MED_ARMOR_DR            = auto()
    MED_ARMOR_HARDENING     = auto()
    MEDIC_HASTE             = auto()
    MELEE_DAMAGE            = auto()
    PISTOL_ACCURACY         = auto()
    PISTOL_COOLING          = auto()
    PISTOL_DAMAGE           = auto()
    SENTINEL_BASTION_HASTE  = auto()
    SENTINEL_HASTE          = auto()
    SHIELD_CAPACITY         = auto()
    SHOTGUN_ACCURACY        = auto()
    SHOTGUN_DAMAGE          = auto()
    SINGULARITY_DURATION    = auto()
    SINGULARITY_HASTE       = auto()
    SINGULARITY_RADIUS      = auto()
    SNIPER_RIFLE_ACCURACY   = auto()
    SNIPER_RIFLE_COOLING    = auto()
    SNIPER_RIFLE_DAMAGE     = auto()
    STASIS_DURATION         = auto()
    STASIS_HASTE            = auto()
    TECH_HASTE              = auto()
    TECH_MINE_DAMAGE        = auto()
    TECH_MINE_HASTE         = auto()
    TECH_MINE_RADIUS        = auto()
    TECH_PROTECTION         = auto()
    THROW_DAMAGE            = auto()
    THROW_FORCE             = auto()
    THROW_HASTE             = auto()
    WARP_DURATION           = auto()
    WARP_HASTE              = auto()


class AbilityLevel(Enum):
    ADRENALINE_BURST    = auto()
    AI_HACKING          = auto()
    ASSASSINATION       = auto()
    BARRIER             = auto()
    CARNAGE             = auto()
    DAMPING             = auto()
    IMMUNITY            = auto()
    LIFT                = auto()
    MARKSMAN            = auto()
    NEURAL_SHOCK        = auto()
    OVERKILL            = auto()
    OVERLOAD            = auto()
    SABOTAGE            = auto()
    SHIELD_BOOST        = auto()
    SINGULARITY         = auto()
    STASIS              = auto()
    THROW               = auto()
    UNITY               = auto()
    WARP                = auto()


class Specialization(Enum):
    ADRENALINE_BURST    = auto()
    ASSASSINATION       = auto()
    BARRIER             = auto()
    FIRST_AID           = auto()
    IMMUNITY            = auto()
    LIFT                = auto()
    NEURAL_SHOCK        = auto()
    OVERLOAD            = auto()
    SABOTAGE            = auto()
    STASIS              = auto()
    WARP                = auto()
